version: "3.9"

services:
  api:
    container_name: "HYPER-MEDIA-API"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - auth
    networks:
      - apinewtork
    restart: always

  auth:
    container_name: "GRPC-AUTH"
    build: ./AuthServer/HyperMediaAuth/
    networks:
      - apinewtork
    depends_on:
      - database
    restart: always

  database:
    container_name: "POSTGRES_DATABASE"
    build: ./AuthServer/HyperMediaAuth/database/
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - apinewtork
    volumes:
      - /var/lib/docker/volumes/postgres/_data:/var/lib/postgresql/data

volumes:
  postgres:
    external: true

networks:
  apinewtork:


