version: "3.9"

services:
  nginx:
    container_name: "NGINX"
    image: nginx
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/
    depends_on:
      - api_1
      - api_2
    networks:
      - apinewtork
      - fetch_network
    restart: always

  api_1:
    container_name: "STOCK-API_1"
    build: .
    environment:
      - NODE=NODE1
      - PORT=8081
      - FETCH_PORT=3001
      - MICROSERVICE_URL=http://microservico_1
    env_file:
      - ".env"
    depends_on:
      - auth
      - microservico_1
    networks:
      - apinewtork
    restart: always

  api_2:
    container_name: "STOCK-API_2"
    build: .
    environment:
      - NODE=NODE2
      - PORT=8082
      - FETCH_PORT=3002
      - MICROSERVICE_URL=http://microservico_2
    depends_on:
      - auth
      - microservico_2
    env_file:
      - ".env"
    networks:
      - apinewtork
    restart: always

  microservico_1:
    container_name: "MICROSERVICE_1"
    build: ./microservicos/stockMicroServico/
    env_file:
      - ./microservicos/stockMicroServico/.env
    environment:
      - PORT=3001
      - NODE=MICROSERVICO1
    networks:
      - apinewtork
      - fetch_network
    depends_on:
      - database
    restart: always

  microservico_2:
    container_name: "MICROSERVICE_2"
    build: ./microservicos/stockMicroServico/
    env_file:
      - ./microservicos/stockMicroServico/.env
    environment:
      - PORT=3002
      - NODE=MICROSERVICO2
    networks:
      - apinewtork
      - fetch_network
    depends_on:
      - database
    restart: always

  auth:
    container_name: "GRPC-AUTH"
    build: ./microservicos/authServer/
    env_file:
      - ./microservicos/authServer/.env
    networks:
      - apinewtork
    depends_on:
      - database
    restart: always

  database:
    container_name: "POSTGRES_DATABASE"
    build: ./microservicos/authServer/database/
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./microservicos/authServer/database/.env
    networks:
      - apinewtork
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    external: false

networks:
  apinewtork:
  fetch_network:
    driver: bridge


