version: "3.9"

services:
  api_1:
    container_name: "STOCK-API_1"
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - FETCH_PORT=3001
      - MICROSERVICE_URL=http://microservico_1
    env_file:
      - ".env"
    depends_on:
      - auth
      - microservico_1
    networks:
      - apinewtork
    restart: always

  microservico_1:
    container_name: "MICROSERVICE_1"
    build: ./microservicos/stockMicroServico/
    ports:
      - "3001:3001"
    env_file:
      - ./microservicos/stockMicroServico/.env
    environment:
      - PORT=3001
    networks:
      - apinewtork
      - fetch_network
    depends_on:
      - database
    restart: always


  auth:
    container_name: "GRPC-AUTH"
    build: ./microservicos/authServer/
    env_file:
      - ./microservicos/authServer/.env
    networks:
      - apinewtork
    depends_on:
      - database
    restart: always

  database:
    container_name: "POSTGRES_DATABASE"
    build: ./microservicos/authServer/database/
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./microservicos/authServer/database/.env
    networks:
      - apinewtork
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
    external: false

networks:
  apinewtork:
  fetch_network:
    driver: bridge


